[project]
name = "launchpad-v1-1"
requirements = []
[repl]
costs_version = 2

[contracts.lottery]
path = "contracts/lottery.clar"
depends_on = ["trait-sip-010", "trait-ido-ft", "token-apower"]

[contracts.trait-sip-010]
path = "contracts_modules/alex_v1/traits/trait-sip-010.clar"
depends_on = [ ]

[contracts.trait-ownable]
path = "contracts_modules/alex_v1/traits/trait-ownable.clar"
depends_on = [ ]

[contracts.token-t-alex]
path = "contracts_modules/alex_v1/token/token-t-alex.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-apower]
path = "contracts_modules/alex_v1/token/token-apower.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-wstx]
path = "contracts_modules/alex_v1/wrapped-token/token-wstx.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-banana]
path = "contracts_modules/alex_v1/token/token-banana.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-wban]
path = "contracts_modules/alex_v1/wrapped-token/token-wban.clar"
depends_on = [ "trait-ownable", "trait-sip-010", "trait-ido-ft", "token-banana" ]

[contracts.trait-ido-ft]
path = "contracts_modules/alex_v1/traits/trait-ido-ft.clar"
depends_on = [ ]






