[project]
name = "alex-v1"
requirements = []

[contracts.trait-semi-fungible-token]
path = "contracts/traits/trait-semi-fungible-token.clar"
depends_on = []

[contracts.margin-helper]
path = "contracts/margin-helper.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "trait-flash-loan-user"]

[contracts.alex-reserve-pool]
path = "contracts/pool/alex-reserve-pool.clar"
depends_on = ["token-alex", "token-usda", "math-fixed-point", "trait-ownable", "trait-sip-010", "alex-vault"]

[contracts.alex-vault]
path = "contracts/alex-vault.clar"
depends_on = ["trait-vault", "trait-sip-010", "trait-flash-loan-user", "math-fixed-point", "trait-ownable", "trait-semi-fungible-token"]

[contracts.collateral-rebalancing-pool]
path = "contracts/pool/collateral-rebalancing-pool.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "trait-vault", "math-fixed-point", "weighted-equation", "fixed-weight-pool", "token-usda", "token-alex", "alex-reserve-pool", "yield-token-pool"]

[contracts.faucet]
path = "contracts/faucet.clar"
depends_on = ["token-wbtc", "token-usda", "token-t-alex", "token-wstx"]

[contracts.fixed-weight-pool]
path = "contracts/pool/fixed-weight-pool.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "math-fixed-point", "weighted-equation", "token-alex", "alex-reserve-pool", "token-usda", "trait-multisig-vote"]

[contracts.liquidity-bootstrapping-pool]
path = "contracts/pool/liquidity-bootstrapping-pool.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "math-fixed-point", "weighted-equation", "token-alex", "alex-reserve-pool", "token-usda", "fixed-weight-pool", "trait-multisig-vote"]

[contracts.math-fixed-point]
path = "contracts/lib/math-fixed-point.clar"
depends_on = ["math-log-exp"]

[contracts.math-log-exp]
path = "contracts/lib/math-log-exp.clar"
depends_on = []

[contracts.math-new-fixed-point]
path = "contracts/new-lib/math-new-fixed-point.clar"
depends_on = ["math-new-log-exp"]

[contracts.math-new-log-exp]
path = "contracts/new-lib/math-new-log-exp.clar"
depends_on = []

[contracts.token-alex]
path = "contracts/token/token-alex.clar"
depends_on = ["trait-pool-token", "trait-ownable"]

[contracts.token-t-alex]
path = "contracts/token/token-t-alex.clar"
depends_on = ["trait-pool-token", "trait-ownable"]

[contracts.token-usda]
path = "contracts/token/token-usda.clar"
depends_on = ["trait-pool-token", "trait-ownable"]

[contracts.token-wbtc]
path = "contracts/token/token-wbtc.clar"
depends_on = ["trait-pool-token", "trait-ownable"]

[contracts.token-wstx]
path = "contracts/token/token-wstx.clar"
depends_on = ["trait-pool-token", "trait-ownable", "alex-vault"]

[contracts.trait-flash-loan-user]
path = "contracts/traits/trait-flash-loan-user.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-multisig-vote]
path = "contracts/traits/trait-multisig-vote.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-oracle]
path = "contracts/traits/trait-oracle.clar"
depends_on = []

[contracts.trait-ownable]
path = "contracts/traits/trait-ownable.clar"
depends_on = []

[contracts.trait-pool-token]
path = "contracts/traits/trait-pool-token.clar"
depends_on = []

[contracts.trait-sip-010]
path = "contracts/traits/trait-sip-010.clar"
depends_on = []

[contracts.trait-vault]
path = "contracts/traits/trait-vault.clar"
depends_on = ["trait-sip-010", "trait-flash-loan-user"]

[contracts.trait-yield-token]
path = "contracts/traits/trait-yield-token.clar"
depends_on = []

[contracts.weighted-equation]
path = "contracts/equations/weighted-equation.clar"
depends_on = ["math-fixed-point"]

[contracts.yield-token-equation]
path = "contracts/equations/yield-token-equation.clar"
depends_on = ["math-fixed-point"]

[contracts.yield-token-pool]
path = "contracts/pool/yield-token-pool.clar"
depends_on = ["trait-sip-010", "trait-vault", "trait-flash-loan-user", "math-fixed-point", "yield-token-equation", "trait-semi-fungible-token", "token-alex", "token-usda", "fixed-weight-pool", "alex-reserve-pool", "trait-multisig-vote"]

[contracts.fwp-wbtc-usda-50-50]
path = "contracts/pool-token/fwp-wbtc-usda-50-50.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-ownable"]

[contracts.lbp-alex-usda-90-10]
path = "contracts/pool-token/lbp-alex-usda-90-10.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-ownable"]

[contracts.ytp-yield-usda]
path = "contracts/pool-token/ytp-yield-usda.clar"
depends_on = ["trait-ownable", "trait-semi-fungible-token"]

[contracts.multisig-fwp-wbtc-usda-50-50]
path = "contracts/multisig/multisig-fwp-wbtc-usda-50-50.clar"
depends_on = []

[contracts.multisig-lbp-alex-usda-90-10]
path = "contracts/multisig/multisig-lbp-alex-usda-90-10.clar"
depends_on = []

[contracts.multisig-crp-usda-wbtc]
path = "contracts/multisig/multisig-crp-usda-wbtc.clar"
depends_on = ["yield-usda", "key-usda-wbtc"]

[contracts.multisig-ytp-yield-usda]
path = "contracts/multisig/multisig-ytp-yield-usda.clar"
depends_on = ["ytp-yield-usda"]

[contracts.key-usda-wbtc]
path = "contracts/key-token/key-usda-wbtc.clar"
depends_on = ["trait-ownable", "trait-semi-fungible-token"]

[contracts.yield-usda]
path = "contracts/yield-token/yield-usda.clar"
depends_on = ["trait-ownable", "trait-semi-fungible-token"]