[project]
name = "alex-v1"
requirements = [ ]
costs_version = 1

[contracts.fixed-weight-pool]
path = "contracts/pool/fixed-weight-pool.clar"
depends_on = [
  "trait-sip-010",
  "trait-vault",
  "math-fixed-point",
  "weighted-equation",
  "token-alex",
  "alex-reserve-pool",
  "token-usda",
  "trait-multisig-vote",
  "token-wstx"
]

[contracts.faucet]
path = "contracts/faucet.clar"
depends_on = [ "token-wbtc", "token-usda", "token-t-alex", "token-wstx" ]

[contracts.alex-launchpad]
path = "contracts/pool/alex-launchpad.clar"
depends_on = [ "trait-ownable", "trait-sip-010", "token-wstx" ]

[contracts.alex-vault]
path = "contracts/alex-vault.clar"
depends_on = [
  "trait-vault",
  "trait-sip-010",
  "trait-flash-loan-user",
  "math-fixed-point",
  "trait-ownable",
  "trait-semi-fungible-token"
]

[contracts.fwp-wstx-usda-50-50]
path = "contracts/pool-token/fwp-wstx-usda-50-50.clar"
depends_on = [ "trait-sip-010", "trait-ownable" ]

[contracts.fwp-wstx-wbtc-50-50]
path = "contracts/pool-token/fwp-wstx-wbtc-50-50.clar"
depends_on = [ "trait-sip-010", "trait-ownable" ]

[contracts.multisig-fwp-wstx-wbtc-50-50]
path = "contracts/multisig/multisig-fwp-wstx-wbtc-50-50.clar"
depends_on = [ ]

[contracts.multisig-fwp-wstx-usda-50-50]
path = "contracts/multisig/multisig-fwp-wstx-usda-50-50.clar"
depends_on = [ ]

[contracts.multisig-crp-usda-wbtc]
path = "contracts/multisig/multisig-crp-usda-wbtc.clar"
depends_on = [ "yield-usda", "key-usda-wbtc" ]

[contracts.collateral-rebalancing-pool]
path = "contracts/pool/collateral-rebalancing-pool.clar"
depends_on = [
  "trait-sip-010",
  "trait-vault",
  "math-fixed-point",
  "weighted-equation",
  "fixed-weight-pool",
  "token-usda",
  "token-alex",
  "alex-reserve-pool",
  "yield-token-pool"
]

[contracts.trait-sip-010]
path = "contracts/traits/trait-sip-010.clar"
depends_on = [ ]

[contracts.trait-vault]
path = "contracts/traits/trait-vault.clar"
depends_on = [ "trait-sip-010", "trait-flash-loan-user" ]

[contracts.math-fixed-point]
path = "contracts/lib/math-fixed-point.clar"
depends_on = [ "math-log-exp" ]

[contracts.weighted-equation]
path = "contracts/equations/weighted-equation.clar"
depends_on = [ "math-fixed-point" ]

[contracts.token-alex]
path = "contracts/token/token-alex.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.alex-reserve-pool]
path = "contracts/pool/alex-reserve-pool.clar"
depends_on = [ "trait-ownable", "trait-sip-010", "alex-vault" ]

[contracts.token-usda]
path = "contracts/token/token-usda.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.trait-multisig-vote]
path = "contracts/traits/trait-multisig-vote.clar"
depends_on = [ "trait-sip-010" ]

[contracts.token-wstx]
path = "contracts/token/token-wstx.clar"
depends_on = [ "trait-ownable", "alex-vault", "trait-sip-010" ]

[contracts.trait-flash-loan-user]
path = "contracts/traits/trait-flash-loan-user.clar"
depends_on = [ "trait-sip-010" ]

[contracts.math-log-exp]
path = "contracts/lib/math-log-exp.clar"
depends_on = [ ]

[contracts.trait-ownable]
path = "contracts/traits/trait-ownable.clar"
depends_on = [ ]

[contracts.trait-semi-fungible-token]
path = "contracts/traits/trait-semi-fungible-token.clar"
depends_on = [ ]

[contracts.token-wbtc]
path = "contracts/token/token-wbtc.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.token-t-alex]
path = "contracts/token/token-t-alex.clar"
depends_on = [ "trait-ownable", "trait-sip-010" ]

[contracts.yield-usda]
path = "contracts/yield-token/yield-usda.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible-token" ]

[contracts.key-usda-wbtc]
path = "contracts/key-token/key-usda-wbtc.clar"
depends_on = [ "trait-ownable", "trait-semi-fungible-token" ]

[contracts.yield-token-pool]
path = "contracts/pool/yield-token-pool.clar"
depends_on = [
  "trait-sip-010",
  "trait-vault",
  "trait-flash-loan-user",
  "math-fixed-point",
  "yield-token-equation",
  "trait-semi-fungible-token",
  "token-alex",
  "token-usda",
  "fixed-weight-pool",
  "alex-reserve-pool",
  "trait-multisig-vote"
]

[contracts.yield-token-equation]
path = "contracts/equations/yield-token-equation.clar"
depends_on = [ "math-fixed-point" ]
