[project]
name = "alex-v1"
requirements = []
[contracts.alex-multisig-registry]
path = "contracts/alex-multisig-registry.clar"
depends_on = ["trait-yield-token", "trait-sip-010"]

[contracts.alex-vault]
path = "contracts/alex-vault.clar"
depends_on = ["trait-vault", "trait-sip-010", "trait-flash-loan-user", "math-fixed-point"]

[contracts.alex-ytp-multisig-vote]
path = "contracts/alex-ytp-multisig-vote.clar"
depends_on = ["trait-multisig-vote", "pool-token-usda-ayusda", "yield-token-pool"]

[contracts.yield-usda-wbtc-4380]
path = "contracts/yield-usda-wbtc-4380.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "token-usda"]

[contracts.collateral-rebalancing-pool]
path = "contracts/collateral-rebalancing-pool.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "trait-vault", "math-fixed-point", "weighted-equation", "open-oracle", "fixed-weight-pool"]

[contracts.fixed-weight-pool]
path = "contracts/fixed-weight-pool.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "math-fixed-point", "weighted-equation"]

[contracts.key-usda-wbtc-4380]
path = "contracts/key-usda-wbtc-4380.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "token-usda"]

[contracts.liquidity-bootstrapping-pool]
path = "contracts/liquidity-bootstrapping-pool.clar"
depends_on = []

[contracts.math-fixed-point]
path = "contracts/math-fixed-point.clar"
depends_on = ["math-log-exp"]

[contracts.math-log-exp]
path = "contracts/math-log-exp.clar"
depends_on = []

[contracts.open-oracle]
path = "contracts/open-oracle.clar"
depends_on = ["trait-yield-token", "trait-oracle", "trait-sip-010"]

[contracts.pool-token-alex-usda]
path = "contracts/pool-token-alex-usda.clar"
depends_on = ["trait-sip-010", "trait-pool-token"]

[contracts.pool-token-ayusda-wbtc]
path = "contracts/pool-token-ayusda-wbtc.clar"
depends_on = ["trait-sip-010", "trait-pool-token"]

[contracts.pool-token-usda-ayusda]
path = "contracts/pool-token-usda-ayusda.clar"
depends_on = ["trait-sip-010", "trait-pool-token"]

[contracts.test-flash-loan-user]
path = "contracts/test-flash-loan-user.clar"
depends_on = ["trait-flash-loan-user", "trait-vault", "trait-sip-010", "alex-vault", "fixed-weight-pool", "token-alex", "token-usda"]

[contracts.token-alex]
path = "contracts/token-alex.clar"
depends_on = ["trait-sip-010", "trait-alex-token"]

[contracts.yield-usda-alex-18530]
path = "contracts/yield-usda-alex-18530.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "token-usda"]

[contracts.token-usda]
path = "contracts/token-usda.clar"
depends_on = ["trait-sip-010", "trait-alex-token"]

[contracts.token-wbtc]
path = "contracts/token-wbtc.clar"
depends_on = ["trait-sip-010", "trait-alex-token"]

[contracts.trait-alex-token]
path = "contracts/trait-alex-token.clar"
depends_on = []

[contracts.trait-flash-loan-user]
path = "contracts/trait-flash-loan-user.clar"
depends_on = []

[contracts.trait-multisig-vote]
path = "contracts/trait-multisig-vote.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-oracle]
path = "contracts/trait-oracle.clar"
depends_on = []

[contracts.trait-pool-token]
path = "contracts/trait-pool-token.clar"
depends_on = []

[contracts.trait-sip-010]
path = "contracts/trait-sip-010.clar"
depends_on = []

[contracts.trait-vault]
path = "contracts/trait-vault.clar"
depends_on = ["trait-sip-010", "trait-flash-loan-user"]

[contracts.trait-yield-token]
path = "contracts/trait-yield-token.clar"
depends_on = []

[contracts.weighted-equation]
path = "contracts/weighted-equation.clar"
depends_on = ["math-fixed-point"]

[contracts.yield-token-equation]
path = "contracts/yield-token-equation.clar"
depends_on = ["math-fixed-point"]

[contracts.yield-token-pool]
path = "contracts/yield-token-pool.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "trait-flash-loan-user", "math-fixed-point", "yield-token-equation", "trait-yield-token", "open-oracle"]

[contracts.multisig-yield-usda-wbtc]
path = "contracts/multisig-yield-usda-wbtc.clar"
depends_on = ["trait-multisig-vote", "pool-token-usda-ayusda", "yield-token-pool"]

[contracts.yield-token-pool-usda-wbtc]
path = "contracts/yield-token-pool-usda-wbtc.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "trait-flash-loan-user", "math-fixed-point", "yield-token-equation", "trait-yield-token"]
