[project]
name = "alex-v1"
requirements = []
[contracts.alex-vault]
path = "contracts/alex-vault.clar"
depends_on = ["trait-vault-flat", "trait-sip-010", "trait-flash-loan-user", "trait-flash-loan-user-mod"]

[contracts.collateral-rebalancing-pool]
path = "contracts/collateral-rebalancing-pool.clar"
depends_on = ["trait-sip-010", "trait-yield-token", "trait-vault", "math-fixed-point", "weighted-equation"]

[contracts.fixed-weight-pool]
path = "contracts/fixed-weight-pool.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "math-fixed-point", "weighted-equation"]

[contracts.flash-loan-v1]
path = "contracts/flash-loan-v1.clar"
depends_on = ["trait-sip-010", "trait-flash-loan-user-mod"]

[contracts.math-fixed-point]
path = "contracts/math-fixed-point.clar"
depends_on = ["math-log-exp"]

[contracts.math-log-exp]
path = "contracts/math-log-exp.clar"
depends_on = []

[contracts.open-oracle]
path = "contracts/open-oracle.clar"
depends_on = ["trait-oracle"]

[contracts.pool-token-alex-usda]
path = "contracts/pool-token-alex-usda.clar"
depends_on = ["trait-sip-010", "trait-pool-token"]

[contracts.token-alex]
path = "contracts/token-alex.clar"
depends_on = ["trait-sip-010", "trait-alex-token"]

[contracts.token-usda]
path = "contracts/token-usda.clar"
depends_on = ["trait-sip-010", "trait-alex-token"]

[contracts.trait-alex-token]
path = "contracts/trait-alex-token.clar"
depends_on = []

[contracts.trait-flash-loan-user]
path = "contracts/trait-flash-loan-user.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-flash-loan-user-mod]
path = "contracts/trait-flash-loan-user-mod.clar"
depends_on = ["trait-sip-010"]

[contracts.trait-oracle]
path = "contracts/trait-oracle.clar"
depends_on = []

[contracts.trait-pool-token]
path = "contracts/trait-pool-token.clar"
depends_on = []

[contracts.trait-sip-010]
path = "contracts/trait-sip-010.clar"
depends_on = []

[contracts.trait-vault]
path = "contracts/trait-vault.clar"
depends_on = ["trait-sip-010", "trait-flash-loan-user"]

[contracts.trait-vault-flat]
path = "contracts/trait-vault-flat.clar"
depends_on = ["trait-sip-010", "trait-flash-loan-user-mod"]

[contracts.trait-yield-token]
path = "contracts/trait-yield-token.clar"
depends_on = []

[contracts.weighted-equation]
path = "contracts/weighted-equation.clar"
depends_on = ["math-fixed-point"]

[contracts.yield-token-equation]
path = "contracts/yield-token-equation.clar"
depends_on = ["math-fixed-point"]

[contracts.yield-token-pool]
path = "contracts/yield-token-pool.clar"
depends_on = ["trait-sip-010", "trait-pool-token", "trait-vault", "math-fixed-point", "yield-token-equation"]
