# GitHub action to verify `clarinet check` runs against contract
# Uses a prepare script outlined in testing section of README

name: CI Clarinet

# Controls when the action will run.
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check contract"
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "cd clarity && clarinet check"
      - name: "Create a shared folder"
        run: mkdir shared
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -v "./shared:/shared" -c "cd clarity && clarinet test --coverage && mv ./coverage.lcov /shared"
      - name: "Upload codecov"
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./shared/coverage.lcov
          fail_ci_if_error: true
          verbose: true
          
