# GitHub action to verify `clarinet check` runs against contract
# Uses a prepare script outlined in testing section of README

name: CI Clarinet

# Controls when the action will run.
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Check contract"
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -c "cd clarity && clarinet check"
      - name: "Execute test suite"
        uses: docker://hirosystems/clarinet:latest
        with:
          entrypoint: "bash"
          args: -e CODECOV_ENV -e CODECOV_TOKEN -e CODECOV_URL -e CODECOV_SLUG -e VCS_COMMIT_ID -e VCS_BRANCH_NAME -e VCS_PULL_REQUEST -e VCS_SLUG -e VCS_TAG -e CI_BUILD_URL -e CI_BUILD_ID -e CI_JOB_ID % -e CI=true -c "cd clarity && clarinet test --coverage && curl -Os https://uploader.codecov.io/v0.1.0_4653/linux/codecov && chmod +x codecov && ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage.lcov"
          
